name: check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v7.0.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.1.0
        with:
          version: 12.8.1
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint & format
        run: pnpm check:ci
      - name: type-check
        run: pnpm type-check
      - name: test
        run: pnpm coverage

      - name: Production build
        run: pnpm build
      - name: Storybook build
        run: pnpm build-storybook
