name: check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Volta
        uses: volta-cli/action@v4
      - name: Setup Node
        run: volta install node
      - name: Setup corepack
        run: volta install corepack@0.31.0
      - name: Setup Pnpm
        run: corepack enable
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint & format
        run: pnpm check:ci
      - name: type-check
        run: pnpm type-check
      - name: test
        run: pnpm run test --run
