name: check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup Pnpm
        run: corepack enable pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint & format
        run: pnpm check:ci
      - name: type-check
        run: pnpm type-check
      - name: test
        run: pnpm run test --run
