# .github/workflows/chromatic.yml

# Workflow name
name: "chromatic"

# Event for the workflow
on:
  pull_request:
    branches: ["master"]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: volta-cli/action@v4
      - name: Setup corepack
        run: volta install corepack@0.31.0
      - name: Setup Pnpm
        run: corepack enable
      - name: install
        run: pnpm install --frozen-lockfile
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
