# .github/workflows/chromatic.yml

# Workflow name
name: "chromatic"

# Event for the workflow
on:
  pull_request:
    branches: ["master"]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.1.0
        with:
          version: 12.8.1
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v18.10.1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
